Schronisko/Schronisko/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Schronisko.Helpers;
using Schronisko.Models;


namespace Schronisko.Controllers
{
    [Authorize]
    public class AdminController : Controller
    {
  
        //OK
        [HttpGet]
        public ActionResult UsersList()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account");
            }

            if ((UserHelper.GetUserRole(User.Identity.Name) != "admin")) { return RedirectToAction("Index", "Home"); }

            pszczupakEntities ent = new pszczupakEntities();

            List<UserViewModel> users = new List<UserViewModel>();

            foreach (Users u in ent.Users.ToList())
            {
                UserViewModel p = new UserViewModel(u);

                users.Add(p);

            }

            return View(users);
        }

        //OK
        [HttpGet]
        public ActionResult UsersRole()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account");
            }

            if ((UserHelper.GetUserRole(User.Identity.Name) != "admin")) { return RedirectToAction("Index", "Home"); }




            pszczupakEntities ent = new pszczupakEntities();

            List<UserViewModel> users = new List<UserViewModel>();

            foreach (Users u in ent.Users.ToList())
            {
                UserViewModel p = new UserViewModel(u);


                if (User.Identity.Name != p.login) { users.Add(p); }
                //  users.Add(p);

            }

            return View(users);

        }

        //OK
        [HttpGet]
        public ActionResult EditRole(int? id)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account");
            }

            if ((UserHelper.GetUserRole(User.Identity.Name) != "admin")) { return RedirectToAction("Index", "Home"); }

            if (id == null)
            {
                return HttpNotFound();
            }


            pszczupakEntities ent = new pszczupakEntities();

            var b = new List<SelectListItem>
            {
                new SelectListItem { Text = "admin", Value = "admin"},
                new SelectListItem { Text = "manager", Value = "manager"},
                new SelectListItem { Text = "worker", Value = "worker"},
                new SelectListItem { Text = "user", Value = "user"}
            };

            ViewData["Roles"] = b;

            

            Users u = ent.Users.Where(x => x.id == id).FirstOrDefault();
            EditRoleModel user = new EditRoleModel();

            ViewBag.login  = u.login;

            user.id = (int)id;
            user.role = u.role;
      

            return View(user);

        }


        //OK
        [HttpPost]
        public ActionResult EditRole(EditRoleModel user)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account");
            }

            if ((UserHelper.GetUserRole(User.Identity.Name) != "admin")) { return RedirectToAction("Index", "Home"); }

            if (ModelState.IsValid)
            {
                pszczupakEntities ent = new pszczupakEntities();
                Users u = new Users();
                u = ent.Users.Where(x => x.id == user.id).FirstOrDefault();

  
                u.role = user.role;
         


                ent.Entry(ent.Users.Where(x => x.id == u.id).First()).CurrentValues.SetValues(u);
                ent.SaveChanges();
                return RedirectToAction("UsersRole");
            }
            else
            {


                pszczupakEntities ent = new pszczupakEntities();
          
                Users u = ent.Users.Where(x => x.id == user.id).FirstOrDefault();

                var b = new List<SelectListItem>
            {
                new SelectListItem { Text = "admin", Value = "admin"},
                new SelectListItem { Text = "manager", Value = "manager"},
                new SelectListItem { Text = "worker", Value = "worker"},
                new SelectListItem { Text = "user", Value = "user"}
            };

                ViewData["Roles"] = b;
                ViewBag.login = u.login;

                return View(user);
            }




        }

        //OK
        [HttpGet]
       public ActionResult DeleteUser(int? id) {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account");
            }

            if ((UserHelper.GetUserRole(User.Identity.Name) != "admin")) { return RedirectToAction("Index", "Home"); }
            if (id == null)
            {
                return HttpNotFound();
            }
            pszczupakEntities ent = new pszczupakEntities();
            UserViewModel model = new UserViewModel(ent.Users.Where(x => x.id == id).FirstOrDefault());

            return View(model);
            
        }

        [HttpGet]
        public ActionResult DeleteConf(int? id)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account");
            }

            if ((UserHelper.GetUserRole(User.Identity.Name) != "admin")) { return RedirectToAction("Index", "Home"); }
            if (id == null)
            {
                return HttpNotFound();
            }
            pszczupakEntities ent = new pszczupakEntities();
            Users user = ent.Users.Where(x => x.id == id).First();
            ent.Users.Remove(user);
            ent.SaveChanges();


            return RedirectToAction("UsersRole");
        }


    }
}

Schronisko/Schronisko/Controllers/DogsController.cs
using Schronisko.Helpers;
using Schronisko.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Schronisko.Controllers
{
    public class DogsController : Controller
    {
        public ActionResult Index()
        {
            pszczupakEntities ent = new pszczupakEntities();
            List<DogsModel> dog = new List<DogsModel>();

            foreach (Dogs d in ent.Dogs.ToList())
                dog.Add(d.ToDogsModelWithID());

            return View(dog);
        }

        [Authorize]
        [HttpGet]
        public ActionResult Create()
        {
            if ((UserHelper.GetUserRole(User.Identity.Name) != "admin")&& (UserHelper.GetUserRole(User.Identity.Name) != "worker")
               && (UserHelper.GetUserRole(User.Identity.Name) != "manager")) { return RedirectToAction("Index", "Home"); }
            {



                DogsModel d = new DogsModel();
                pszczupakEntities ent = new pszczupakEntities();
                ViewData["Race"] = ent.Races.Select(x => new SelectListItem() { Value = x.id.ToString(), Text = x.name }).ToList();

                return View(d);
            }
        }

        [Authorize]
        [HttpPost]
        public ActionResult Create(DogsModel d, HttpPostedFileBase file)
        {

            if ((UserHelper.GetUserRole(User.Identity.Name) != "admin") && (UserHelper.GetUserRole(User.Identity.Name) != "worker")
               && (UserHelper.GetUserRole(User.Identity.Name) != "manager")) { return RedirectToAction("Index", "Home"); }
            { 

            if (ModelState.IsValid)
            {
     
                pszczupakEntities ent = new pszczupakEntities();
                Dogs dog = d.ToDogsWithoutID();
                ent.Dogs.Add(dog);
                ent.SaveChanges();

                if (file != null)
                {
                    var path = Path.Combine(Server.MapPath($"~/Images/Dogs/Index/{dog.id}"), file.FileName);
                    System.IO.Directory.CreateDirectory(Server.MapPath($"~/Images/Dogs/Index/{dog.id}"));
                    file.SaveAs(path);
                    dog.photo_path = $"/Images/Dogs/Index/{dog.id}/{file.FileName}";
                }

                ent.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                pszczupakEntities ent = new pszczupakEntities();
                ViewData["Race"] = ent.Races.Select(x => new SelectListItem() { Value = x.id.ToString(), Text = x.name }).ToList();

                return View(d);
            }

            }

        }

        [Authorize]
        [HttpGet]
        public ActionResult Edit(int? Id)
        {
            if ((UserHelper.GetUserRole(User.Identity.Name) != "admin") && (UserHelper.GetUserRole(User.Identity.Name) != "worker")
               && (UserHelper.GetUserRole(User.Identity.Name) != "manager")) { return RedirectToAction("Index", "Home"); }
            if (Id == null)
            {
                return HttpNotFound();
            }

            pszczupakEntities ent = new pszczupakEntities();
            DogsModel dog = ent.Dogs.Where(x => x.id == Id).FirstOrDefault().ToDogsModelWithID();
            ViewData["Race"] = ent.Races.Select(x => new SelectListItem() { Value = x.id.ToString(), Text = x.name }).ToList();
           
            return View(dog);
        }

        [Authorize]
        [HttpPost]
        public ActionResult Edit(DogsModel dog, HttpPostedFileBase file)
        {
            if ((UserHelper.GetUserRole(User.Identity.Name) != "admin") && (UserHelper.GetUserRole(User.Identity.Name) != "worker")
               && (UserHelper.GetUserRole(User.Identity.Name) != "manager")) { return RedirectToAction("Index", "Home"); }


            if (ModelState.IsValid)
            {
                if (file != null)
                {
                    var path = Path.Combine(Server.MapPath($"~/Images/Dogs/Index/{dog.id}"), file.FileName);
                    System.IO.Directory.CreateDirectory(Server.MapPath($"~/Images/Dogs/Index/{dog.id}"));
                    file.SaveAs(path);
                }
                    pszczupakEntities ent = new pszczupakEntities();
                    Dogs d = new Dogs();
                    d = ConverterHelper.ToDogsWithID(dog);

                if (file != null)
                d.photo_path = $"/Images/Dogs/Index/{dog.id}/{file.FileName}";


                    ent.Entry(ent.Dogs.Where(x => x.id == d.id).First()).CurrentValues.SetValues(d);
                    ent.SaveChanges();
                

               return RedirectToAction("Index");
            }
            else
            {
                pszczupakEntities ent = new pszczupakEntities();
                ViewData["Race"] = ent.Races.Select(x => new SelectListItem() { Value = x.id.ToString(), Text = x.name }).ToList();

                return View(dog);
            }
        }


        [HttpGet]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            pszczupakEntities ent = new pszczupakEntities();
            DogsModel model = ent.Dogs.Where(x => x.id == id).FirstOrDefault().ToDogsModelWithID();
            return View(model);
        }

        [Authorize]
        [HttpGet]
        public ActionResult Delete(int? id)
        {
            if ((UserHelper.GetUserRole(User.Identity.Name) != "admin") && (UserHelper.GetUserRole(User.Identity.Name) != "worker")
                && (UserHelper.GetUserRole(User.Identity.Name) != "manager")) { return RedirectToAction("Index", "Home"); }

            if (id == null)
            {
                return HttpNotFound();
            }
            pszczupakEntities ent = new pszczupakEntities();
            DogsModel model = ent.Dogs.Where(x => x.id == id).FirstOrDefault().ToDogsModelWithID();
            return View(model);
            //Dogs dog = ent.Dogs.Where(x => x.id == id).First();
            //ent.Dogs.Remove(dog);
            //ent.SaveChanges();
            //return RedirectToAction("Index");
        }
        [Authorize]
        [HttpGet]
        public ActionResult DeleteConf(int? id)
        {
            if ((UserHelper.GetUserRole(User.Identity.Name) != "admin") && (UserHelper.GetUserRole(User.Identity.Name) != "worker")
                && (UserHelper.GetUserRole(User.Identity.Name) != "manager")) { return RedirectToAction("Index", "Home"); }

            if (id == null)
            {
                return HttpNotFound();
            }
            pszczupakEntities ent = new pszczupakEntities();
            Dogs dog = ent.Dogs.Where(x => x.id == id).First();
            ent.Dogs.Remove(dog);
            ent.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Schronisko/Schronisko/Controllers/UsersEventsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Schronisko;
using Schronisko.Models;
using Schronisko.Helpers;

namespace Schronisko.Controllers
{
    public class UsersEventsController : Controller
    {
        
        public ActionResult Index()
        {
            if ((UserHelper.GetUserRole(User.Identity.Name) != "admin") && (UserHelper.GetUserRole(User.Identity.Name) != "manager"))
            { return RedirectToAction("Index", "Home"); }

            pszczupakEntities ent = new pszczupakEntities();
            List<UsersEventsModel> ue = new List<UsersEventsModel>();


            foreach (UsersEvents m in ent.UsersEvents.ToList())
            {
                ue.Add(new UsersEventsModel(m));
            }
            
            return View(ue);
        }

        [Authorize]
        [HttpGet]
        public ActionResult Create()
        {
            if ((UserHelper.GetUserRole(User.Identity.Name) != "admin") && (UserHelper.GetUserRole(User.Identity.Name) != "manager"))
            { return RedirectToAction("Index", "Home"); }

            if (UserHelper.GetUserRole(User.Identity.Name) == "" || User == null)
            {
                return RedirectToAction("Index", "Home");
            }

            UsersEventsModel e = new UsersEventsModel();


            pszczupakEntities ent = new pszczupakEntities();
            ViewData["U"] = ent.Users.Select(x => new SelectListItem() { Value = x.id.ToString(), Text = x.name }).ToList();
            ViewData["E"] = ent.Events.Select(x => new SelectListItem() { Value = x.id.ToString(), Text = x.description }).ToList();

      
            return View(e);

        }

        [Authorize]
        [HttpPost]
        public ActionResult Create(UsersEventsModel e)
        {
            if ((UserHelper.GetUserRole(User.Identity.Name) != "admin") && (UserHelper.GetUserRole(User.Identity.Name) != "manager"))
            { return RedirectToAction("Index", "Home"); }


            pszczupakEntities ent = new pszczupakEntities();

            if (ModelState.IsValid)
            {

             UsersEvents eventt = new UsersEvents();
                eventt.id_event = e.id_event;
                eventt.id_user = e.id_user;
                ent.UsersEvents.Add(eventt);
                ent.SaveChanges();

                return RedirectToAction("Index");
            }
            else
            {
      
                ViewData["U"] = ent.Users.Select(x => new SelectListItem() { Value = x.id.ToString(), Text = x.name }).ToList();
                ViewData["E"] = ent.Events.Select(x => new SelectListItem() { Value = x.id.ToString(), Text = x.description }).ToList();


                return View(e);
            }


        }

        [Authorize]
        [HttpGet]
        public ActionResult Delete(int? id)
        {
            if ((UserHelper.GetUserRole(User.Identity.Name) != "admin") && (UserHelper.GetUserRole(User.Identity.Name) != "worker")
               && (UserHelper.GetUserRole(User.Identity.Name) != "manager")) { return RedirectToAction("Index", "Home"); }

            if (!id.HasValue)
                return HttpNotFound();

            pszczupakEntities ent = new pszczupakEntities();
            UsersEvents ue = ent.UsersEvents.Where(x => x.id == id).First();
            ent.UsersEvents.Remove(ue);
            ent.SaveChanges();
            return RedirectToAction("Index");
        }



        //[HttpGet]
        //public ActionResult Details(int id)
        //{
        //    pszczupakEntities ent = new pszczupakEntities();
        //    UsersEventsModel model = ent.UsersEvents.Where(x => x.id == id).FirstOrDefault().ToUsersEventsModelWithID();
        //    int eve = ent.UsersEvents.Where(x => x.id == id).Select(x => x.id_event).FirstOrDefault();
        //    List<int> usersID = ent.UsersEvents.Where(y => y.id_event == eve ).Select(x => x.id_user).ToList();

        //    List<Users> users = new List<Users>();
        //    Users user = new Users();
        //    foreach (int ID in usersID)
        //    {
        //        user = ent.Users.Where(x=> x.id == ID).FirstOrDefault();
        //        users.Add(user);
        //    }

        //    ViewData["U"] = users;
        //    return View(model);

        //}






    }
}

Schronisko/Schronisko/Views/Shared/_IndexLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <link href="https://fonts.googleapis.com/css?family=Mali" rel="stylesheet">
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Psi Raj</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <style>
        body, html {
            height: 100%;
            margin: 0;
        }

        * {
            box-sizing: border-box;
        }

        .bg-image { /* The image used */
            background-image: url(../Images/Tosiowe/tlo.jpg);
            /* Add the blur effect */
            filter: blur(1px);
            -webkit-filter: blur(1px);
            /* Full height */
            height: 100%;
            /* Center and scale the image nicely */
            background-position: center;
            background-repeat: no-repeat;
            background-size: cover;
            z-index: -1;
        }

        /* Position text in the middle of the page/image */
        .bg-text {
            background-color: rgb(0,0,0); /* Fallback color */
            background-color: rgba(0,0,0, 0.5); /* Black w/opacity/see-through */
            color: antiquewhite;
            font-weight: bold;
            border-bottom: 3px solid #a2ae55;
            border-top: 3px solid #a2ae55;
            position: absolute;
            top: 43%;
            left: 50%;
            transform: translate(-50%, -50%);
            width: 100%;
            padding: 20px;
            text-align: center;
            font-family: Mali;
        }
    </style>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Psi Raj", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Psy", "Index", "Dogs")</li>
                    <li>@Html.ActionLink("Rasy", "Index", "Races")</li>
                    <li>@Html.ActionLink("O Nas", "About", "Home")</li>
                    <li>@Html.ActionLink("Kontakt", "Contact", "Home")</li>
                    @if (Schronisko.Helpers.UserHelper.GetUserRole(User.Identity.Name) != "")
                    {
                        <li>@Html.ActionLink("Harmonogram", "Schedule", "Events")</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>


    <div class="bg-image"><span style="font-size:30px;cursor:pointer" onclick="openNav()">&#9776;</span></div>

    

    @if (Schronisko.Helpers.UserHelper.GetUserRole(User.Identity.Name) == "admin" ||
         Schronisko.Helpers.UserHelper.GetUserRole(User.Identity.Name) == "manager" ||
         Schronisko.Helpers.UserHelper.GetUserRole(User.Identity.Name) == "worker")
    {
        <span style="font-size:30px;cursor:pointer" onclick="openNav()">&#9776;</span>
        <div id="mySidenav" class="sidenav">
            <a>Zamknij:</a>
            <a href="#">@Html.ActionLink("Psy", "Index", "Dogs")</a>
            <a href="#">@Html.ActionLink("Rasy", "Index", "Races")</a>
            @if (Schronisko.Helpers.UserHelper.GetUserRole(User.Identity.Name) == "admin" || Schronisko.Helpers.UserHelper.GetUserRole(User.Identity.Name) == "manager")
            {
                <a href="#">@Html.ActionLink("Harmonogram", "Schedule", "Events")</a>
                <a href="#">@Html.ActionLink("Dodaj pracownika do wydarzenia", "Index", "UsersEvents")</a>
            }
            @if (Schronisko.Helpers.UserHelper.GetUserRole(User.Identity.Name) == "admin")
            {
                <a href="#">@Html.ActionLink("Użytkownicy", "UsersRole", "Admin")</a>

            }
            <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
        </div>
    }
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Psi Raj, Schronisko dla psów</p>
        </footer>
    </div>
    <script>
        function openNav() {
            document.getElementById("mySidenav").style.width = "200px";
            document.getElementById("main").style.marginLeft = "200px";
        }

        function closeNav() {
            document.getElementById("mySidenav").style.width = "0";
            document.getElementById("main").style.marginLeft = "0";
        }
    </script>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)


    <script>
        function w3_open() {
            document.getElementById("mySidebar").style.display = "block";
        }

        function w3_close() {
            document.getElementById("mySidebar").style.display = "none";
        }
    </script>


</body>
</html>

Schronisko/Schronisko/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Psi Raj</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Psi Raj", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Psy", "Index", "Dogs")</li>
                    <li>@Html.ActionLink("Rasy", "Index", "Races")</li>
                    <li>@Html.ActionLink("O Nas", "About", "Home")</li>
                    <li>@Html.ActionLink("Kontakt", "Contact", "Home")</li>
                    @if (Schronisko.Helpers.UserHelper.GetUserRole(User.Identity.Name) != "")
                    {
                        <li>@Html.ActionLink("Harmonogram", "Schedule", "Events")</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>


    @if (Schronisko.Helpers.UserHelper.GetUserRole(User.Identity.Name) == "admin" ||
         Schronisko.Helpers.UserHelper.GetUserRole(User.Identity.Name) == "manager" ||
         Schronisko.Helpers.UserHelper.GetUserRole(User.Identity.Name) == "worker")
    {
            <span style="font-size:30px;cursor:pointer" onclick="openNav()">&#9776;</span>
            <div id="mySidenav" class="sidenav">
                <a>Zamknij:</a>
                <a href="#">@Html.ActionLink("Psy", "Index", "Dogs")</a>
                <a href="#">@Html.ActionLink("Rasy", "Index", "Races")</a>
                @if (Schronisko.Helpers.UserHelper.GetUserRole(User.Identity.Name) == "worker")
                {
                    <a href="#">@Html.ActionLink("Harmonogram", "Schedule", "Events")</a>
                }


                @if (Schronisko.Helpers.UserHelper.GetUserRole(User.Identity.Name) == "admin" || Schronisko.Helpers.UserHelper.GetUserRole(User.Identity.Name) == "manager")
                {
                    <a href="#">@Html.ActionLink("Harmonogram", "Schedule", "Events")</a>
                    <a href="#">@Html.ActionLink("Dodaj pracownika do wydarzenia", "Index", "UsersEvents")</a>
                }
                @if (Schronisko.Helpers.UserHelper.GetUserRole(User.Identity.Name) == "admin")
                {
                    <a href="#">@Html.ActionLink("Użytkownicy", "UsersRole", "Admin")</a>

                }
                <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
            </div>
        }
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Psi Raj, Schronisko dla psów</p>
        </footer>
    </div>
    <script>
        function openNav() {
            document.getElementById("mySidenav").style.width = "200px";
            document.getElementById("main").style.marginLeft = "200px";
        }

        function closeNav() {
            document.getElementById("mySidenav").style.width = "0";
            document.getElementById("main").style.marginLeft = "0";
        }
    </script>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)


    <script>
        function w3_open() {
            document.getElementById("mySidebar").style.display = "block";
        }

        function w3_close() {
            document.getElementById("mySidebar").style.display = "none";
        }
    </script>


</body>
</html>
