Schronisko/Schronisko/Controllers/DogsController.cs
using Schronisko.Helpers;
using Schronisko.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Schronisko.Controllers
{
    public class DogsController : Controller
    {
        public ActionResult Index()
        {
            pszczupakEntities ent = new pszczupakEntities();
            List<DogsModel> dog = new List<DogsModel>();

            foreach (Dogs d in ent.Dogs.ToList())
                dog.Add(d.ToDogsModelWithID());

            return View(dog);
        }

        [Authorize]
        [HttpGet]
        public ActionResult Create()
        {
            if ((UserHelper.GetUserRole(User.Identity.Name) != "admin")&& (UserHelper.GetUserRole(User.Identity.Name) != "worker")
               && (UserHelper.GetUserRole(User.Identity.Name) != "manager")) { return RedirectToAction("Index", "Home"); }
            {



                DogsModel d = new DogsModel();
                pszczupakEntities ent = new pszczupakEntities();
                ViewData["Race"] = ent.Races.Select(x => new SelectListItem() { Value = x.id.ToString(), Text = x.name }).ToList();

                return View(d);
            }
        }

        [Authorize]
        [HttpPost]
        public ActionResult Create(DogsModel d, HttpPostedFileBase file)
        {

            if ((UserHelper.GetUserRole(User.Identity.Name) != "admin") && (UserHelper.GetUserRole(User.Identity.Name) != "worker")
               && (UserHelper.GetUserRole(User.Identity.Name) != "manager")) { return RedirectToAction("Index", "Home"); }
            { 

            if (ModelState.IsValid)
            {
     
                pszczupakEntities ent = new pszczupakEntities();
                Dogs dog = d.ToDogsWithoutID();
                ent.Dogs.Add(dog);
                ent.SaveChanges();

                if (file != null)
                {
                    var path = Path.Combine(Server.MapPath($"~/Images/Dogs/Index/{dog.id}"), file.FileName);
                    System.IO.Directory.CreateDirectory(Server.MapPath($"~/Images/Dogs/Index/{dog.id}"));
                    file.SaveAs(path);
                    dog.photo_path = $"/Images/Dogs/Index/{dog.id}/{file.FileName}";
                }

                ent.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                pszczupakEntities ent = new pszczupakEntities();
                ViewData["Race"] = ent.Races.Select(x => new SelectListItem() { Value = x.id.ToString(), Text = x.name }).ToList();

                return View(d);
            }

            }

        }

        [Authorize]
        [HttpGet]
        public ActionResult Edit(int? Id)
        {
            if ((UserHelper.GetUserRole(User.Identity.Name) != "admin") && (UserHelper.GetUserRole(User.Identity.Name) != "worker")
               && (UserHelper.GetUserRole(User.Identity.Name) != "manager")) { return RedirectToAction("Index", "Home"); }
            if (Id == null)
            {
                return HttpNotFound();
            }

            pszczupakEntities ent = new pszczupakEntities();
            DogsModel dog = ent.Dogs.Where(x => x.id == Id).FirstOrDefault().ToDogsModelWithID();
            ViewData["Race"] = ent.Races.Select(x => new SelectListItem() { Value = x.id.ToString(), Text = x.name }).ToList();
           
            return View(dog);
        }

        [Authorize]
        [HttpPost]
        public ActionResult Edit(DogsModel dog, HttpPostedFileBase file)
        {
            if ((UserHelper.GetUserRole(User.Identity.Name) != "admin") && (UserHelper.GetUserRole(User.Identity.Name) != "worker")
               && (UserHelper.GetUserRole(User.Identity.Name) != "manager")) { return RedirectToAction("Index", "Home"); }


            if (ModelState.IsValid)
            {
                if (file != null)
                {
                    var path = Path.Combine(Server.MapPath($"~/Images/Dogs/Index/{dog.id}"), file.FileName);
                    System.IO.Directory.CreateDirectory(Server.MapPath($"~/Images/Dogs/Index/{dog.id}"));
                    file.SaveAs(path);
                }
                    pszczupakEntities ent = new pszczupakEntities();
                    Dogs d = new Dogs();
                    d = ConverterHelper.ToDogsWithID(dog);

                if (file != null)
                d.photo_path = $"/Images/Dogs/Index/{dog.id}/{file.FileName}";


                    ent.Entry(ent.Dogs.Where(x => x.id == d.id).First()).CurrentValues.SetValues(d);
                    ent.SaveChanges();
                

               return RedirectToAction("Index");
            }
            else
            {
                pszczupakEntities ent = new pszczupakEntities();
                ViewData["Race"] = ent.Races.Select(x => new SelectListItem() { Value = x.id.ToString(), Text = x.name }).ToList();

                return View(dog);
            }
        }


        [HttpGet]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            pszczupakEntities ent = new pszczupakEntities();
            DogsModel model = ent.Dogs.Where(x => x.id == id).FirstOrDefault().ToDogsModelWithID();
            return View(model);
        }

        [Authorize]
        [HttpGet]
        public ActionResult Delete(int? id)
        {
            if ((UserHelper.GetUserRole(User.Identity.Name) != "admin") && (UserHelper.GetUserRole(User.Identity.Name) != "worker")
                && (UserHelper.GetUserRole(User.Identity.Name) != "manager")) { return RedirectToAction("Index", "Home"); }

            if (id == null)
            {
                return HttpNotFound();
            }
            pszczupakEntities ent = new pszczupakEntities();
            DogsModel model = ent.Dogs.Where(x => x.id == id).FirstOrDefault().ToDogsModelWithID();
            return View(model);
            //Dogs dog = ent.Dogs.Where(x => x.id == id).First();
            //ent.Dogs.Remove(dog);
            //ent.SaveChanges();
            //return RedirectToAction("Index");
        }
        [Authorize]
        [HttpGet]
        public ActionResult DeleteConf(int? id)
        {
            if ((UserHelper.GetUserRole(User.Identity.Name) != "admin") && (UserHelper.GetUserRole(User.Identity.Name) != "worker")
                && (UserHelper.GetUserRole(User.Identity.Name) != "manager")) { return RedirectToAction("Index", "Home"); }

            if (id == null)
            {
                return HttpNotFound();
            }
            pszczupakEntities ent = new pszczupakEntities();
            Dogs dog = ent.Dogs.Where(x => x.id == id).First();
            ent.Dogs.Remove(dog);
            ent.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Schronisko/Schronisko/Controllers/RacesController.cs
using Schronisko.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Windows;
using Schronisko.Helpers;

namespace Schronisko.Controllers
{
    public class RacesController : Controller
    {
        // GET: Races
        public ActionResult Index()
        {
            pszczupakEntities ent = new pszczupakEntities();
            List<RacesModel> race = new List<RacesModel>();


            foreach (Races r in ent.Races.ToList())    
                race.Add(r.ToRacesModelWithID());
            
            return View(race);
        }

        public PartialViewResult RacePartial(int id)
        {
            pszczupakEntities ent = new pszczupakEntities();
            RacesModel model = ent.Races.Where(x => x.id == id).FirstOrDefault().ToRacesModelWithID();
            return PartialView("DetailAboutRace",model);
        }

        [Authorize]
        [HttpGet]
        public ActionResult Create()
        {
            if ((UserHelper.GetUserRole(User.Identity.Name) != "admin") && (UserHelper.GetUserRole(User.Identity.Name) != "worker")
               && (UserHelper.GetUserRole(User.Identity.Name) != "manager")) { return RedirectToAction("Index", "Home"); }

            RacesModel r = new RacesModel();
            return View(r);

        }
        
        [Authorize]
        [HttpPost]
        public ActionResult Create(RacesModel r)
        {
            if ((UserHelper.GetUserRole(User.Identity.Name) != "admin") && (UserHelper.GetUserRole(User.Identity.Name) != "worker")
               && (UserHelper.GetUserRole(User.Identity.Name) != "manager")) { return RedirectToAction("Index", "Home"); }


            if (ModelState.IsValid)
            {
                pszczupakEntities ent = new pszczupakEntities();
                ent.Races.Add(r.ToRacesWithoutID());
                ent.SaveChanges();


                return RedirectToAction("Index");
            }
            else
            {
                return View(r);
            }


        }

        [Authorize]
        [HttpGet]
        public ActionResult Edit(int? Id)
        {
            if ((UserHelper.GetUserRole(User.Identity.Name) != "admin") && (UserHelper.GetUserRole(User.Identity.Name) != "worker")
               && (UserHelper.GetUserRole(User.Identity.Name) != "manager")) { return RedirectToAction("Index", "Home"); }

            if (Id == null)
            {
                return HttpNotFound();
            }
            pszczupakEntities ent = new pszczupakEntities();
            RacesModel race = ent.Races.Where(x => x.id == Id).FirstOrDefault().ToRacesModelWithID();
            return View(race);
        }

        [Authorize]
        [HttpPost]
        public ActionResult Edit(RacesModel race)
        {
            if ((UserHelper.GetUserRole(User.Identity.Name) != "admin") && (UserHelper.GetUserRole(User.Identity.Name) != "worker")
               && (UserHelper.GetUserRole(User.Identity.Name) != "manager")) { return RedirectToAction("Index", "Home"); }


            if (ModelState.IsValid) 
            {
                pszczupakEntities ent = new pszczupakEntities();
                Races r = ent.Races.Where(x => x.id == race.id).FirstOrDefault();
                r = ConverterHelper.RacesSameValuesWithoutID(r, race);
                ent.Entry(ent.Races.Where(x => x.id == r.id).First()).CurrentValues.SetValues(r);
                ent.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                return View(race);
            }
        }


        [HttpGet]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            pszczupakEntities ent = new pszczupakEntities();
            RacesModel model = ent.Races.Where(x => x.id == id).FirstOrDefault().ToRacesModelWithID();
            return View(model);
        }

        [Authorize]
        [HttpGet]
        public ActionResult Delete(int? id)
        {
            if ((UserHelper.GetUserRole(User.Identity.Name) != "admin") && (UserHelper.GetUserRole(User.Identity.Name) != "worker")
               && (UserHelper.GetUserRole(User.Identity.Name) != "manager")) { return RedirectToAction("Index", "Home"); }

            if (id == null)
            {
                return HttpNotFound();
            }
            pszczupakEntities ent = new pszczupakEntities();
            RacesModel race = ent.Races.Where(x => x.id == id).FirstOrDefault().ToRacesModelWithID();

            return View(race);
        }
        [Authorize]
        [HttpGet]
        public ActionResult DeleteConf(int? id)
        {
            if ((UserHelper.GetUserRole(User.Identity.Name) != "admin") && (UserHelper.GetUserRole(User.Identity.Name) != "worker")
               && (UserHelper.GetUserRole(User.Identity.Name) != "manager")) { return RedirectToAction("Index", "Home"); }
            if (id == null)
            {
                return HttpNotFound();
            }

            pszczupakEntities ent = new pszczupakEntities();
            Races race = ent.Races.Where(x => x.id == id).First();

            List<Dogs> dogs = ent.Dogs.Where(x => x.id_race == id).ToList();

            foreach (Dogs d in dogs)
            {
                d.id_race = null;
                ent.Entry(ent.Dogs.Where(x => x.id == d.id).First()).CurrentValues.SetValues(d);
            }

            ent.Races.Remove(race);
            ent.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

Schronisko/Schronisko/Views/Dogs/Create.cshtml
@model Schronisko.Models.DogsModel

@{
    ViewBag.Title = "Dodaj Pieska";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Dodaj psa</h2>

@using (Html.BeginForm("Create", "Dogs", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4></h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.year_of_birth, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.year_of_birth, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.year_of_birth, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.photo_path, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
               <input type="file" name="file" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.id_race, htmlAttributes: new { @class = "control-label col-md-2" })

            <div class="col-md-10">
                @Html.DropDownListFor(model => model.id_race, ((List<SelectListItem>)ViewData["Race"]), new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.races.name, "", new { @class = "text-danger" })
            </div>

        </div>


        @*<div class="form-group">
                @Html.LabelFor(model => model.id_race, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.id_race, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.id_race, "", new { @class = "text-danger" })
                </div>
            </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Dodaj" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Wróć", "Index")
</div>

Schronisko/Schronisko/Views/Dogs/Delete.cshtml
@model Schronisko.Models.DogsModel

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Usuwanie</h2>

<h3>Czy napewno chcesz usunąć tego psa?</h3>


<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.year_of_birth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.year_of_birth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.id_race)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.races.name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        @Html.ActionLink("Usuń", "DeleteConf", new { id = Model.id }) |
        @Html.ActionLink("Wróć", "Index")
    </div>
    }
</div>

Schronisko/Schronisko/Views/Dogs/Details.cshtml
@model Schronisko.Models.DogsModel

@{
    ViewBag.Title = "Szczegóły Pieska";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Szczegóły o psie</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.year_of_birth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.year_of_birth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.photo_path)
        </dt>

        <dd>
            <img style="display: block; margin: 20px; width:350px;height: auto; float:left " src="@Model.photo_path" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.id_race)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.races.name)
        </dd>

    </dl>
</div>
<p>

    @Html.ActionLink("Edytuj", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Usuń", "Delete", new { id = Model.id }) |
    @Html.ActionLink("Wróć", "Index")
</p>

<div class="row">
    @*@Html.Action("RacePartial","Races", new { id = Model.id_race})*@
    @Html.Action("RacePartial", "Races", new { id = Model.id_race })
</div>

Schronisko/Schronisko/Views/Dogs/Edit.cshtml
@model Schronisko.Models.DogsModel

@{
    ViewBag.Title = "Edytuj Pieska";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edycja Psa</h2>

@using (Html.BeginForm("Edit","Dogs",FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.id)
    @Html.HiddenFor(model => model.photo_path)


    <div class="form-group">
        @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.year_of_birth, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.year_of_birth, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.year_of_birth, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Zdjęcie", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="file" />
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.id_race, htmlAttributes: new { @class = "control-label col-md-2" })

        <div class="col-md-10">
            @Html.DropDownListFor(model => model.id_race, ((List<SelectListItem>)ViewData["Race"]), new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.races.name, "", new { @class = "text-danger" })
        </div>

    </div>
    @*<div class="form-group">
            @Html.LabelFor(model => model.id_race, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.id_race, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.id_race, "", new { @class = "text-danger" })
            </div>
        </div>*@

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Zapisz" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Wróć", "Index")
</div>

Schronisko/Schronisko/Views/Dogs/Index.cshtml
@model IEnumerable<Schronisko.Models.DogsModel>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_RacesLayout.cshtml";
}
<div class="bg-text">
    <h2>Psy znajdujące się w schronisku</h2>
    @if (Schronisko.Helpers.UserHelper.GetUserRole(User.Identity.Name) == "admin" ||
         Schronisko.Helpers.UserHelper.GetUserRole(User.Identity.Name) == "manager" ||
         Schronisko.Helpers.UserHelper.GetUserRole(User.Identity.Name) == "worker")
    {
        <p>
            @Html.ActionLink("Dodaj psa", "Create")
        </p>
    }
</div>

    @foreach (var item in Model)
    {
        if (!item.name.Equals(""))
        {
            <div class="bg-text" style=" overflow: auto">

                <img style="display: block; margin: 20px; width:350px;height: auto; float:left " src="@item.photo_path" />

                <div style="margin-top:25px">
                    <p>
                        <h4>Imie: @Html.DisplayFor(modelItem => item.name)</h4>
                    </p>
                    <p>
                        <h4>Rok urodzenia: @Html.DisplayFor(modelItem => item.year_of_birth)</h4>
                    </p>
                    @*<p>
                        @Html.DisplayFor(modelItem => item.photo_path)
                    </p>*@
                    <p>
                        <h4>Opis: @Html.DisplayFor(modelItem => item.description)</h4>
                    </p>
                    <p>
                        <h4>Rasa: @Html.DisplayFor(modelItem => item.races.name)</h4>
                    </p>
                    @if (Schronisko.Helpers.UserHelper.GetUserRole(User.Identity.Name) == "admin" ||
                     Schronisko.Helpers.UserHelper.GetUserRole(User.Identity.Name) == "manager" ||
                     Schronisko.Helpers.UserHelper.GetUserRole(User.Identity.Name) == "worker")
                    {
                        <p>
                            @Html.ActionLink("Edytuj", "Edit", new { id = item.id }) |
                            @Html.ActionLink("Szczegóły", "Details", new { id = item.id }) |
                            @Html.ActionLink("Skasuj", "Delete", new { id = item.id })
                        </p>
                    }
                    </div>

            </div>
        }
    }





@*<table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.year_of_birth)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.photo_path)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.id_race)
            </th>
            <th></th>
        </tr>

    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.year_of_birth)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.photo_path)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.races.name)
            </td>
            <td>
                @Html.ActionLink("Edytuj", "Edit", new { id=item.id }) |
                @Html.ActionLink("Szczegóły", "Details", new { id=item.id }) |
                @Html.ActionLink("Skasuj", "Delete", new { id=item.id })
            </td>
        </tr>
    }

    </table>*@